### PR TITLE
Score to main form

### PR DESCRIPTION
**Pull request by pauliusanuzas**
Added scoreLabel that displays user score in mainForm.

### CODE REVIEW

**Comment by aurisgo** [comment]
Listen, update method doesn't work.

**Comment by pauliusanuzas** [comment]
Listen, I didn't write that method. I was the one who found this bug. Please fix it when you have time.

**Comment by pauliusanuzas** [comment]
HAVE A NICE DAY

**Comment by aurisgo** [comment]
It's night

**Comment by pauliusanuzas** [comment]
Out of Lithuania for business trip, my bad.

**Comment by aurisgo** [comment]
unilad-pirate83309-640x426

#metoo

**Review by modestas-jucevicius — COMMENTED** [review]
Please add images to .gitignore and remove them from repository

**Review by modestas-jucevicius — APPROVED** [review]

**Pull request closed without merging**
